use_frameworks!

target 'ErrorDispatching_Example' do
  pod 'ErrorDispatching/ReactiveSwift', :path => '../'
  pod 'ErrorDispatching/Moya', :path => '../'

  target 'ErrorDispatching_Tests' do
    inherit! :search_paths

    
  end
end
